### ISSUE TITLE
[通用模板] - 首页 & 目录导航

### ISSUE THREAD

**Issue by xiaosansiji** [TDesignOteam/tdesign-miniprogram-starter#1]
## 设计稿地址

【腾讯 CoDesign】移动端活动报名页面模版
https://codesign.qq.com/s/2bzpZvlE2b9kAaV
访问密码：UMOD

## 页面截图

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/3cc76e94-6e5e-4809-b169-2b1ea91ba328)

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/0bacfd2b-abe1-4c57-8bd4-4607fd1664f1)

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/b5d595a2-4397-4f90-9019-cf2306ae2e85)

报名请在本 issue 回复“我认领，预期在 xxx 时间前提交 PR”，预期时间尽量明确且选择较近的日期，临近时间未提交时会协调其他同学投入完成。最终页面完成以关联在本 issue PR 被接受合入为准。

**Comment by Yuuki-Yuuna** [comment]
我认领，预计在8月28日前提交PR

**Comment by LeeJim** [comment]
fixed by #14
