### ISSUE TITLE
[通用模板] - 发布

### ISSUE THREAD

**Issue by xiaosansiji** [TDesignOteam/tdesign-miniprogram-starter#2]
## 设计稿地址

【腾讯 CoDesign】移动端活动报名页面模版
https://codesign.qq.com/s/2bzpZvlE2b9kAaV
访问密码：UMOD

## 页面截图

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/ee294348-de67-4af6-bfc1-df94902da7e9)

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/f50b2505-82fa-429b-bc6c-b473b6efdc4a)

报名请在本 issue 回复“我认领，预期在 xxx 时间前提交 PR”，预期时间尽量明确且选择较近的日期，临近时间未提交时会协调其他同学投入完成。最终页面完成以关联在本 issue PR 被接受合入为准。

**Comment by liangweijing** [comment]
我认领，预期在 8月21日前提交 PR
