### ISSUE TITLE
[通用模板] - 个人信息维护

### ISSUE THREAD

**Issue by xiaosansiji** [TDesignOteam/tdesign-miniprogram-starter#6]
## 设计稿地址

【腾讯 CoDesign】移动端活动报名页面模版
https://codesign.qq.com/s/2bzpZvlE2b9kAaV
访问密码：UMOD

## 页面截图

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/d3167387-7e7b-4d4a-a374-d9440ffd073b)
![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/eecc4e06-e2da-492c-8133-e8a0a275bd57)

报名请在本 issue 回复“我认领，预期在 xxx 时间前提交 PR”，预期时间尽量明确且选择较近的日期，临近时间未提交时会协调其他同学投入完成。最终页面完成以关联在本 issue PR 被接受合入为准。

**Comment by imp2002** [comment]
认领，预期在 2023-08-22 前提交 PR
