### ISSUE TITLE
[通用模板] - 登录

### ISSUE THREAD

**Issue by xiaosansiji** [TDesignOteam/tdesign-miniprogram-starter#9]
## 设计稿地址

【腾讯 CoDesign】移动端活动报名页面模版
https://codesign.qq.com/s/2bzpZvlE2b9kAaV
访问密码：UMOD

## 页面截图

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/e9658ba4-d198-4e94-966b-8314902b1a00)

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/48d45417-fb5c-4434-8e71-77c06587340b)

![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7600149/f1a214b7-4a57-409e-a51c-58a3055aab36)

报名请在本 issue 回复“我认领，预期在 xxx 时间前提交 PR”，预期时间尽量明确且选择较近的日期，临近时间未提交时会协调其他同学投入完成。最终页面完成以关联在本 issue PR 被接受合入为准。

贡献完成同学：@xxxx
参与贡献同学：@yyy

**Comment by shinyina** [comment]
我认领，预期在 8月13日前提交 PR
